export const ADD_RESERVATION = 'ADD_RESERVATION';
export const REMOVE_RESERVATION = 'REMOVE_RESERVATION';
export const RECEIVE_RESERVATIONS = 'RECEIVE_RESERVATIONS';
export const RECEIVE_ROCKETS = 'RECEIVE_ROCKETS';
export const RECEIVE_DRAGONS = 'RECEIVE_DRAGONS';
export const RECEIVE_MISSIONS = 'RECEIVE_MISSIONS';
